#!/usr/bin/env zsh
echo "start pre-commit."

echo "🚀 Running format checks..."
npm run format
if [ $? -ne 0 ]; then
  echo "👎 format failed. Aborting commit."
  exit 1
fi
echo "👍 format checks passed."

echo "🚀 Running lint checks..."
npm run lint
if [ $? -ne 0 ]; then
  echo "👎 lint failed. Aborting commit."
  exit 1
fi
echo "👍 lint checks passed."

necho "🚀 Running type checks..."
npm run check:types
if [ $? -ne 0 ]; then
  echo "👎 type-checks failed. Aborting commit."
  exit 1
fi
echo "👍 type checks passed."